### ISSUE TITLE
Clarify that the debanding won't have an effect when using GLES3

### ISSUE THREAD

**Issue by Calinou** [fractilegames/godot-gles2-debanding-material#1]
I believe this line disables the debanding part when using GLES3: https://github.com/fractilegames/godot-gles2-debanding-material/blob/main/debandingmaterial.shader#L27

This should be either documented in the README, or always enabled. You may need debanding when using GLES3 when HDR is disabled in the project settings (to improve performance), or when using GLES3 on mobile to workaround the [built-in debanding shader not working](https://github.com/godotengine/godot/issues/45366).

**Comment by fractilegames** [comment]
You're right. I only wanted this enabled with GLES2 in my original game project. It should be always enabled here.
